### ISSUE TITLE
Day 2 notes

### ISSUE THREAD

**Issue by carriewright11** [fhdsl/SeattleStatSummer_R#8]
Great job again!

Data Import
- maybe it would be helpful to pause after the project section for them to make one? and check in on them
- some JHU links that we maybe want to update: slide 15 and 16
- I wasn't paying enough attention but maybe the url https://github.com/fhdsl/SeattleStatSummer_R/raw/main/data/tb_incidence.xlsx needed to be changed I think to the https://github.com/fhdsl/SeattleStatSummer_R/data/tb_incidence.xlsx (or the example was the other way around?)

Data Summarization
- maybe add pipe to the summary 
- if they aren't getting it (which hopefully they are!) could simplify to things like `state_data %>% pull(cancer_rate_per_100000) %>% range(na.rm = TRUE)` instead of using summarize
- could add these functions/tips to the cheatsheet for the day

**Comment by avahoffman** [comment]
Thank you!!! Great ideas.

> if they aren't getting it (which hopefully they are!) could simplify to things like state_data %>% pull(cancer_rate_per_100000) %>% range(na.rm = TRUE) instead of using summarize

I didn't cover `pull()` since I thought we were already covering a lot. Do you think it's essential?

> I wasn't paying enough attention but maybe the url https://github.com/fhdsl/SeattleStatSummer_R/raw/main/data/tb_incidence.xlsx needed to be changed I think to the https://github.com/fhdsl/SeattleStatSummer_R/data/tb_incidence.xlsx (or the example was the other way around?)

It should be https://hutchdatascience.org/SeattleStatSummer_R/data/tb_incidence.xlsx .. the github links don't work, weirdly

**Comment by carriewright11** [comment]
> Thank you!!! Great ideas.
> 
> > if they aren't getting it (which hopefully they are!) could simplify to things like state_data %>% pull(cancer_rate_per_100000) %>% range(na.rm = TRUE) instead of using summarize
> 
> I didn't cover `pull()` since I thought we were already covering a lot. Do you think it's essential?
> 
> > I wasn't paying enough attention but maybe the url https://github.com/fhdsl/SeattleStatSummer_R/raw/main/data/tb_incidence.xlsx needed to be changed I think to the https://github.com/fhdsl/SeattleStatSummer_R/data/tb_incidence.xlsx (or the example was the other way around?)
> 
> It should be https://hutchdatascience.org/SeattleStatSummer_R/data/tb_incidence.xlsx .. the github links don't work, weirdly


I ended up needing to cover pull for my material, so it could be useful to just show there is another way, but not essential - it was mostly if people found summarize confusing- as they sometimes do.
